[package]
name = "lista4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "7.1.0"
entropy = { version = "0.1.0", path = "../entropy" }
log = "0.4.20"
rayon = "1.8.0"
